// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breadcrumb': string;
  'breadcrumbLink': string;
  'breadcrumbSeparator': string;
  'code': string;
  'codeBlock': string;
  'content': string;
  'homeCard': string;
  'homeCardDescription': string;
  'homeCardTitle': string;
  'homeGrid': string;
  'list': string;
  'listItem': string;
  'noteBox': string;
  'paragraph': string;
  'section': string;
  'sectionTitle': string;
  'sidebar': string;
  'sidebarItem': string;
  'sidebarLink': string;
  'sidebarLinkActive': string;
  'sidebarList': string;
  'tip': string;
  'tipContent': string;
  'warningBox': string;
  'wikiContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
