// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formatProfiles': string;
  'profileHeader': string;
  'profileSection': string;
  'profileTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
