// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formatProfiles': string;
  'profileLabel': string;
  'profileText': string;
  'qualityName': string;
}
export const cssExports: CssExports;
export default cssExports;
